In [7]:
from functions import *
path = "jester-data-1.csv"
df = pd.read_csv(path, header=None)
df.replace(99, pd.NA, inplace=True)
num_rev = df.pop(0)
df_na = df.copy()
df = df.fillna(0)
df = df.sample(n = 1000)

In [85]:
df = df.reset_index().drop("index", axis =1)

In [83]:
user = 3
user_ser = df.iloc[user]
sims = []

for i in range(df.shape[0]):
    sim = user_ser.corr(df.iloc[i])
    sims.append(sim)

sims = pd.Series(sims)
sims = sims.drop(user)
i = sims.nlargest(5).index
i

sims.iloc[i].abs().sum()

0.7143249745124833

In [92]:
df.at[(1,3)]

-0.15

In [95]:
df_na

,1,2,3,4,5,6,7,8,9,10,...,91,92,93,94,95,96,97,98,99,100
0,-7.82,8.79,-9.66,-8.16,-7.52,-8.5,-9.85,4.17,-8.98,-4.76,...,2.82,<NA>,<NA>,<NA>,<NA>,<NA>,-5.63,<NA>,<NA>,<NA>
1,4.08,-0.29,6.36,4.37,-2.38,-9.66,-0.73,-5.34,8.88,9.22,...,2.82,-4.95,-0.29,7.86,-0.19,-2.14,3.06,0.34,-4.32,1.07
2,<NA>,<NA>,<NA>,<NA>,9.03,9.27,9.03,9.27,<NA>,<NA>,...,<NA>,<NA>,<NA>,9.08,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
3,<NA>,8.35,<NA>,<NA>,1.8,8.16,-2.82,6.21,<NA>,1.84,...,<NA>,<NA>,<NA>,0.53,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
4,8.5,4.61,-4.17,-5.39,1.36,1.6,7.04,4.61,-0.44,5.73,...,5.19,5.58,4.27,5.19,5.73,1.55,3.11,6.55,1.8,1.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24978,0.44,7.43,9.08,2.33,3.2,6.75,-8.79,-0.53,-8.74,7.23,...,8.83,-1.21,9.22,-6.7,8.45,9.03,6.55,8.69,8.79,7.43
24979,9.13,-8.16,8.59,9.08,0.87,-8.93,-3.5,5.78,-8.11,4.9,...,-1.17,-5.73,-1.46,0.24,9.22,-8.2,-7.23,-8.59,9.13,8.45
24980,<NA>,<NA>,<NA>,<NA>,-7.77,<NA>,6.7,-6.75,<NA>,<NA>,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
24981,<NA>,<NA>,<NA>,<NA>,-9.71,<NA>,4.56,-8.3,<NA>,<NA>,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
24982,2.43,2.67,-3.98,4.27,-2.28,7.33,2.33,4.56,6.75,4.61,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>

In [96]:
users = [1, 1,2]
items = [1,3, 5]
[df.at[user, items] for user, items in zip(users, items)]

[-9.22, -0.15, -5.87]

In [73]:
c =  3
user = 1
curr_avrg = df_na.drop(c, axis = 1).iloc[user].mean(skipna= True)
df_na.iloc[user].mean()

2.7463000000000006

In [75]:
df_test = df_na.copy().fillna(0)

In [77]:
df_test

,1,2,3,4,5,6,7,8,9,10,...,91,92,93,94,95,96,97,98,99,100
0,-7.82,8.79,-9.66,-8.16,-7.52,-8.50,-9.85,4.17,-8.98,-4.76,...,2.82,0.00,0.00,0.00,0.00,0.00,-5.63,0.00,0.00,0.00
1,4.08,-0.29,6.36,4.37,-2.38,-9.66,-0.73,-5.34,8.88,9.22,...,2.82,-4.95,-0.29,7.86,-0.19,-2.14,3.06,0.34,-4.32,1.07
2,0.00,0.00,0.00,0.00,9.03,9.27,9.03,9.27,0.00,0.00,...,0.00,0.00,0.00,9.08,0.00,0.00,0.00,0.00,0.00,0.00
3,0.00,8.35,0.00,0.00,1.80,8.16,-2.82,6.21,0.00,1.84,...,0.00,0.00,0.00,0.53,0.00,0.00,0.00,0.00,0.00,0.00
4,8.50,4.61,-4.17,-5.39,1.36,1.60,7.04,4.61,-0.44,5.73,...,5.19,5.58,4.27,5.19,5.73,1.55,3.11,6.55,1.80,1.60
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24978,0.44,7.43,9.08,2.33,3.20,6.75,-8.79,-0.53,-8.74,7.23,...,8.83,-1.21,9.22,-6.70,8.45,9.03,6.55,8.69,8.79,7.43
24979,9.13,-8.16,8.59,9.08,0.87,-8.93,-3.50,5.78,-8.11,4.90,...,-1.17,-5.73,-1.46,0.24,9.22,-8.20,-7.23,-8.59,9.13,8.45
24980,0.00,0.00,0.00,0.00,-7.77,0.00,6.70,-6.75,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
24981,0.00,0.00,0.00,0.00,-9.71,0.00,4.56,-8.30,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
24982,2.43,2.67,-3.98,4.27,-2.28,7.33,2.33,4.56,6.75,4.61,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00

In [101]:
import csv
filename = "test_cases.csv"
cases = []
with open(filename, 'r') as file:
    csv_reader = csv.reader(file)

    for line in csv_reader:
        # 'line' is a list representing a row in the CSV file
        cases.append((int(line[0]), int(line[1])))

cases

[(1, 50), (75, 34), (100, 8), (25, 20), (1010, 33)]

In [102]:
data = {'Name': ['Alice', 'Bob', 'Charlie', 'David'],
        'Age': [25, 30, 22, 28],
        'City': ['New York', 'San Francisco', 'Los Angeles', 'Chicago']}

df = pd.DataFrame(data)

# Print each row, including the header
for index, row in df.iterrows():
    print(f"Row {index + 1}:")
    for column, value in row.items():
        print(f"  {column}: {value}")
    print()

Row 1:
  Name: Alice
  Age: 25
  City: New York

Row 2:
  Name: Bob
  Age: 30
  City: San Francisco

Row 3:
  Name: Charlie
  Age: 22
  City: Los Angeles

Row 4:
  Name: David
  Age: 28
  City: Chicago

In [103]:
from io import StringIO

# Example: Creating a DataFrame
data = {'Name': ['Alice', 'Bob', 'Charlie', 'David'],
        'Age': [25, 30, 22, 28],
        'City': ['New York', 'San Francisco', 'Los Angeles', 'Chicago']}

df = pd.DataFrame(data)

# Convert DataFrame to CSV format with header
csv_output = StringIO()
df.to_csv(csv_output, index=False, header=True)

# Print each line
csv_lines = csv_output.getvalue().split('\n')
for line in csv_lines:
    print(line)

Name,Age,City
Alice,25,New York
Bob,30,San Francisco
Charlie,22,Los Angeles
David,28,Chicago

In [104]:
import os
from datetime import datetime

# Get the current time
current_time = datetime.now()

# Format the current time as a string (e.g., "2023-11-15_12-34-56")
formatted_time = current_time.strftime("%Y-%m-%d_%H-%M-%S")

# Create the folder
folder_name =  "outputs/" + formatted_time
try:
    os.makedirs(folder_name)
    print(f"Folder '{folder_name}' created successfully.")
except Exception as e:
    print(f"An error occurred: {e}")

Folder 'outputs/2023-11-16_10-51-23' created successfully.

In [11]:
import os
from datetime import datetime

def init_dir():
    curr_time = datetime.now()
    folder_name = curr_time.strftime("%d_%H-%M-%S")
    outputs_folder = os.path.join(os.getcwd(), "outputs")

    folder_path = os.path.join(outputs_folder, folder_name)
    os.mkdir(folder_path)
    print(f"Successfully created folder: {folder_name}")
    return folder_path
    
path = init_dir()

Successfully created folder: 17_13-11-44

In [12]:
path

'/Users/sorenpaetau/Desktop/csc466lab5/outputs/17_13-11-44'

In [13]:
# Example usage
# Assuming you have a DataFrame named 'your_dataframe'
df = pd.DataFrame({
    'Column1': [1, 2, 3],
    'Column2': ['A', 'B', 'C']
}) 

csv_file_path = os.path.join(path, 'data.csv')
    
# Write the DataFrame to the CSV file
df.to_csv(csv_file_path, index=False)
print(f"DataFrame successfully written to {csv_file_path}")

DataFrame successfully written to /Users/sorenpaetau/Desktop/csc466lab5/outputs/17_13-11-44/data.csv

In [14]:
name = 13
name = f"iter{name}.csv"
name

'iter13.csv'

In [20]:
import pandas as pd
path = "Spotify_data.xlsx"
dfin = pd.read_excel(path)
df = dfin[['Age', 'Gender', 'spotify_usage_period', 'preferred_listening_content',
       'spotify_subscription_plan', 'fav_music_genre', 'music_time_slot', 'music_Influencial_mood',
       'music_lis_frequency', 'music_expl_method', 'music_recc_rating']]
df

,Age,Gender,spotify_usage_period,preferred_listening_content,spotify_subscription_plan,fav_music_genre,music_time_slot,music_Influencial_mood,music_lis_frequency,music_expl_method,music_recc_rating
0,20-35,Female,More than 2 years,Podcast,Free (ad-supported),Melody,Night,Sadness or melancholy,leisure time,Playlists,3
1,12-20,Male,More than 2 years,Podcast,Free (ad-supported),Rap,Afternoon,Social gatherings or parties,Workout session,Playlists,2
2,35-60,Others,6 months to 1 year,Podcast,Free (ad-supported),Pop,Night,Relaxation and stress relief,"Study Hours, While Traveling",Playlists,4
3,20-35,Female,1 year to 2 years,Music,Free (ad-supported),Melody,Night,"Relaxation and stress relief, Social gathering...","Office hours, Workout session, leisure time","recommendations, Playlists",4
4,20-35,Female,1 year to 2 years,Music,Free (ad-supported),Melody,Night,Relaxation and stress relief,leisure time,"recommendations, Playlists",4
...,...,...,...,...,...,...,...,...,...,...,...
515,20-35,Female,More than 2 years,Music,Free (ad-supported),Pop,Morning,"Uplifting and motivational, Sadness or melancholy",While Traveling,recommendations,5
516,20-35,Female,More than 2 years,Music,Free (ad-supported),Pop,Night,"Relaxation and stress relief, Uplifting and mo...","While Traveling, Workout session, leisure time",Others,2
517,20-35,Female,More than 2 years,Music,Free (ad-supported),Pop,Night,Relaxation and stress relief,leisure time,recommendations,3
518,20-35,Female,6 months to 1 year,Music,Premium (paid subscription),Melody,Night,"Relaxation and stress relief, Uplifting and mo...","Workout session, leisure time","recommendations, Others",2
519,20-35,Female,More than 2 years,Music,Premium (paid subscription),Pop,Night,"Relaxation and stress relief, Sadness or melan...","Office hours,Study Hours, While Traveling, lei...","Playlists, Radio",3

In [17]:
df.columns

Index(['Age', 'Gender', 'spotify_usage_period', 'spotify_listening_device',
       'spotify_subscription_plan', 'premium_sub_willingness',
       'preffered_premium_plan', 'preferred_listening_content',
       'fav_music_genre', 'music_time_slot', 'music_Influencial_mood',
       'music_lis_frequency', 'music_expl_method', 'music_recc_rating'],
      dtype='object')

NameError: name 'dfin' is not defined

In [15]:
dumcols = ['music_Influencial_mood','music_lis_frequency', 'music_expl_method']
for col in dumcols:
    df_dummies = df[col].str.get_dummies(',')

    # Concatenate the dummy columns with the original DataFrame
    df = pd.concat([df, df_dummies], axis=1)
    df.drop(col, axis=1, inplace=True)

,Age,Gender,spotify_usage_period,spotify_listening_device,spotify_subscription_plan,premium_sub_willingness,preffered_premium_plan,preferred_listening_content,fav_music_genre,music_time_slot,music_lis_frequency,music_expl_method,music_recc_rating,Relaxation and stress relief,Sadness or melancholy,Social gatherings or parties,Uplifting and motivational
0,20-35,Female,More than 2 years,Smart speakers or voice assistants,Free (ad-supported),Yes,Family Plan-Rs 179/month,Podcast,Melody,Night,leisure time,Playlists,3,0,1,0,0
1,12-20,Male,More than 2 years,Computer or laptop,Free (ad-supported),Yes,Individual Plan- Rs 119/ month,Podcast,Rap,Afternoon,Workout session,Playlists,2,0,0,1,0
2,35-60,Others,6 months to 1 year,Smart speakers or voice assistants,Free (ad-supported),Yes,Student Plan-Rs 59/month,Podcast,Pop,Night,"Study Hours, While Traveling",Playlists,4,1,0,0,0
3,20-35,Female,1 year to 2 years,"Smartphone, Smart speakers or voice assistants",Free (ad-supported),No,NaN,Music,Melody,Night,"Office hours, Workout session, leisure time","recommendations, Playlists",4,1,0,1,0
4,20-35,Female,1 year to 2 years,Smartphone,Free (ad-supported),No,NaN,Music,Melody,Night,leisure time,"recommendations, Playlists",4,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
515,20-35,Female,More than 2 years,"Smartphone, Computer or laptop, Wearable devices",Free (ad-supported),Yes,Student Plan-Rs 59/month,Music,Pop,Morning,While Traveling,recommendations,5,0,1,0,1
516,20-35,Female,More than 2 years,"Smartphone, Computer or laptop",Free (ad-supported),Yes,Student Plan-Rs 59/month,Music,Pop,Night,"While Traveling, Workout session, leisure time",Others,2,1,1,1,1
517,20-35,Female,More than 2 years,Smartphone,Free (ad-supported),No,Student Plan-Rs 59/month,Music,Pop,Night,leisure time,recommendations,3,1,0,0,0
518,20-35,Female,6 months to 1 year,Smartphone,Premium (paid subscription),Yes,Individual Plan- Rs 119/ month,Music,Melody,Night,"Workout session, leisure time","recommendations, Others",2,1,0,0,1
519,20-35,Female,More than 2 years,"Smartphone, Computer or laptop",Premium (paid subscription),Yes,Student Plan-Rs 59/month,Music,Pop,Night,"Office hours,Study Hours, While Traveling, lei...","Playlists, Radio",3,1,1,0,0

In [7]:
test = pd.get_dummies(df2)
test * 1

,music_recc_rating,Age_12-20,Age_20-35,Age_35-60,Age_6-12,Age_60+,Gender_Female,Gender_Male,Gender_Others,spotify_usage_period_1 year to 2 years,...,music_expl_method_recommendations,"music_expl_method_recommendations, Others","music_expl_method_recommendations, Others, Social media","music_expl_method_recommendations, Playlists","music_expl_method_recommendations, Playlists, Others","music_expl_method_recommendations, Playlists, Radio","music_expl_method_recommendations, Playlists, Radio, Others","music_expl_method_recommendations, Radio","music_expl_method_recommendations, Radio, Others","music_expl_method_recommendations,Others, Social media"
0,3,0,1,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,2,1,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
2,4,0,0,1,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
3,4,0,1,0,0,0,1,0,0,1,...,0,0,0,1,0,0,0,0,0,0
4,4,0,1,0,0,0,1,0,0,1,...,0,0,0,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
515,5,0,1,0,0,0,1,0,0,0,...,1,0,0,0,0,0,0,0,0,0
516,2,0,1,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
517,3,0,1,0,0,0,1,0,0,0,...,1,0,0,0,0,0,0,0,0,0
518,2,0,1,0,0,0,1,0,0,0,...,0,1,0,0,0,0,0,0,0,0
519,3,0,1,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
def normalize_column(column):
    return (column - column.min()) / (column.max() - column.min())

path = "Spotify_data.xlsx"
dfin = pd.read_excel(path)
df = dfin[['Age', 'Gender', 'spotify_usage_period', 'preferred_listening_content',
       'spotify_subscription_plan', 'music_time_slot', 'music_Influencial_mood',
       'music_lis_frequency', 'music_expl_method', 'music_recc_rating', 'fav_music_genre']]
genres = df["fav_music_genre"].unique()
numgenres = len(genres)


dumcols = ['music_Influencial_mood','music_lis_frequency', 'music_expl_method']
for col in dumcols:
    df_dummies = df[col].str.get_dummies(',')
    df_dummies.columns = df_dummies.columns.str.strip()
    df_dummies = df_dummies.add_prefix(col+"_")

    # Concatenate the dummy columns with the original DataFrame
    df = pd.concat([df, df_dummies], axis=1)
    df.drop(col, axis=1, inplace=True)

df["music_recc_rating"] = normalize_column(df["music_recc_rating"])



dumm = pd.get_dummies(df) * 1
dumm.columns = dumm.columns.str.replace(" ", "_")

dumm.to_csv("dummified_user.csv", index=False)
dumm.columnsimport pandas as pd
import numpy as np

# Defining the genres
genres = ["EDM", "Country", "Pop", "HipHop", "Film", "Classical", "Religious", "Latin", "Rock", "Jazz", "R&B", "Soul", "Folk"]

# Creating a DataFrame to hold the dataset

# Populating the dataset
np.random.seed(0)  # For reproducibility
n = 152
    # Base ratings with some randomness
ratings = {
    "EDM": np.random.normal(4, 2, n).astype(int),  # Mean: 7, Standard Deviation: 2
    "Country": np.random.normal(5, 2, n).astype(int),  # Mean: 5, Standard Deviation: 2
    "Pop": np.random.normal(7.5, 2, n).astype(int),  # Mean: 6, Standard Deviation: 2
    "HipHop": np.random.normal(8, 4, n).astype(int),  # Mean: 8, Standard Deviation: 1.5
    "Film": np.random.normal(5, 2, n).astype(int),  # Mean: 5, Standard Deviation: 2
    "Classical": np.random.normal(5, 2, n).astype(int),  # Mean: 3, Standard Deviation: 1.5
    "Religious": np.random.normal(4, 2, n).astype(int),  # Mean: 4, Standard Deviation: 2
    "Latin": np.random.normal(6, 1.5, n).astype(int),  # Mean: 6, Standard Deviation: 1.5
    "Rock": np.random.normal(7, 1.5, n).astype(int),  # Mean: 7, Standard Deviation: 1.5
    "Jazz": np.random.normal(5, 2, n).astype(int),  # Mean: 5, Standard Deviation: 2
    "R&B": np.random.normal(6, 2, n).astype(int),  # Mean: 6, Standard Deviation: 2
    "Soul": np.random.normal(5, 2, n).astype(int),  # Mean: 5, Standard Deviation: 2
    "Folk": np.random.normal(4, 1.5, n).astype(int) 
}

# Adjusting ratings based on genre affinity
m1 = ratings["Pop"] > 7
ratings["HipHop"][m1] += 1
ratings["R&B"][m1] += 1
ratings["Folk"] -= 1
ratings["Classical"] -= 1

m2 = ratings["Classical"] > 5
ratings["Film"][m2] += 1
ratings["Jazz"][m2] += 2

m3 = ratings["Rock"] > 6
ratings["EDM"][m3] += 1
ratings["Folk"][m3] += 1

m4 = ratings["Jazz"] > 7
ratings["Pop"][m4] += 1
ratings["R&B"][m4] += 1
ratings["Folk"][m4] -= 1
ratings["Rock"][m4] -= 1

m5 = ratings["Rock"] > 8
ratings["EDM"][m5] += 2
ratings["Pop"][m5] -= 1
ratings["Classical"][m5] -= 1

m6 = ratings["HipHop"] > 6
ratings["Rock"][m6] += 1
ratings["Jazz"][m6] += 1
ratings["Folk"][m6] -= 1
ratings["Film"][m6] -= 1

# Ensuring ratings are within 1-10
sd = np.zeros(numgenres)
for i, genre in enumerate(genres):
    ratings[genre] = np.minimum(10, ratings[genre])
    ratings[genre] = np.maximum(1, ratings[genre])
    sd[i] = np.std(ratings[genre])


# Adding the row to the dataset
dataset = pd.DataFrame(ratings)

dataset.to_csv("spotify_ratings.csv", index=False)